// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/socialite/socialite.proto

package socialite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Socialite service

type SocialiteService interface {
	// 小程序获取授权
	Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 授权网址
	AuthURL(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Handle(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type socialiteService struct {
	c    client.Client
	name string
}

func NewSocialiteService(name string, c client.Client) SocialiteService {
	return &socialiteService{
		c:    c,
		name: name,
	}
}

func (c *socialiteService) Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Socialite.Auth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialiteService) AuthURL(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Socialite.AuthURL", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialiteService) Handle(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Socialite.Handle", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Socialite service

type SocialiteHandler interface {
	// 小程序获取授权
	Auth(context.Context, *Request, *Response) error
	// 授权网址
	AuthURL(context.Context, *Request, *Response) error
	Handle(context.Context, *Request, *Response) error
}

func RegisterSocialiteHandler(s server.Server, hdlr SocialiteHandler, opts ...server.HandlerOption) error {
	type socialite interface {
		Auth(ctx context.Context, in *Request, out *Response) error
		AuthURL(ctx context.Context, in *Request, out *Response) error
		Handle(ctx context.Context, in *Request, out *Response) error
	}
	type Socialite struct {
		socialite
	}
	h := &socialiteHandler{hdlr}
	return s.Handle(s.NewHandler(&Socialite{h}, opts...))
}

type socialiteHandler struct {
	SocialiteHandler
}

func (h *socialiteHandler) Auth(ctx context.Context, in *Request, out *Response) error {
	return h.SocialiteHandler.Auth(ctx, in, out)
}

func (h *socialiteHandler) AuthURL(ctx context.Context, in *Request, out *Response) error {
	return h.SocialiteHandler.AuthURL(ctx, in, out)
}

func (h *socialiteHandler) Handle(ctx context.Context, in *Request, out *Response) error {
	return h.SocialiteHandler.Handle(ctx, in, out)
}
